export const FETCH_SERVERS_REQUEST = "FETCH_SERVERS_REQUEST";
export const FETCH_SERVERS_SUCCESS = "FETCH_SERVERS_SUCCESS";
export const FETCH_SERVERS_FAILURE = "FETCH_SERVERS_FAILURE";
export const DELETE_ATTENDEE_REQUEST = "DELETE_ATTENDEE_REQUEST";
export const DELETE_ATTENDEE_SUCCESS = "DELETE_ATTENDEE_SUCCESS";
export const DELETE_ATTENDEE_FAILURE = "DELETE_ATTENDEE_FAILURE";
