export const SET_HAS_BEEN_SCANNED = "SET_HAS_BEEN_SCANNED";
export const SET_HAS_BEEN_SCANNED_SUCCESS = "SET_HAS_BEEN_SCANNED_SUCCESS";
export const SET_HAS_BEEN_SCANNED_FAILURE = "SET_HAS_BEEN_SCANNED_FAILURE";
export const FETCH_PARTICIPANTS = "FETCH_PARTICIPANTS";
export const FETCH_PARTICIPANTS_SUCCESS = "FETCH_PARTICIPANTS_SUCCESS";
export const FETCH_PARTICIPANTS_FAILURE = "FETCH_PARTICIPANTS_FAILURE";
