export const FETCH_PARTICIPANTS_REQUEST = "FETCH_PARTICIPANTS_REQUEST";
export const FETCH_PARTICIPANTS_SUCCESS = "FETCH_PARTICIPANTS_SUCCESS";
export const FETCH_PARTICIPANTS_FAILURE = "FETCH_PARTICIPANTS_FAILURE";
