export const CREATE_PARTICIPANT_REQUEST = "CREATE_PARTICIPANT_REQUEST";
export const CREATE_PARTICIPANT_SUCCESS = "CREATE_PARTICIPANT_SUCCESS";
export const CREATE_PARTICIPANT_FAILURE = "CREATE_PARTICIPANT_FAILURE";
