export const CREATE_PARTICIPANT = "CREATE_PARTICIPANT";
export const CREATE_PARTICIPANT_SUCCESS = "CREATE_PARTICIPANT_SUCCESS";
export const CREATE_PARTICIPANT_FAILURE = "CREATE_PARTICIPANT_FAILURE";
